---
fixtures:
  repositories:
    stdlib:
      ref: "4.18.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    firewall:
      ref: "1.9.0"
      repo: "https://github.com/puppetlabs/puppetlabs-firewall"
  symlinks:
    vision_firewall: '#{source_dir}'
