---
fixtures:
  repositories:
    stdlib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    firewall:
      ref: "v2.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-firewall"
  symlinks:
    vision_firewall: '#{source_dir}'
